# Generated by Django 3.1.7 on 2021-05-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areatienda', '0003_alter_tienda_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='user',
        ),
    ]
