# Generated by Django 3.1.7 on 2021-05-14 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_remove_productos_usuario'),
        ('areatienda', '0004_remove_tienda_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.productos'),
        ),
    ]
