# Generated by Django 3.1.7 on 2021-05-14 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_productos_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='usuario',
        ),
    ]
