# Generated by Django 3.2 on 2021-05-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
