# Generated by Django 3.1.7 on 2021-05-13 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areatienda', '0004_remove_tienda_user'),
        ('usuarios', '0003_delete_tienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='AreaTienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='areatienda.tienda'),
        ),
    ]
